### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by liamxg** [Dokandres/EcuadorNPI#1]
<img width="712" alt="image" src="https://user-images.githubusercontent.com/46078579/222897638-92722118-bccb-41c6-9b4c-32642aed9378.png">

**Comment by liamxg** [comment]
@Dokandres

**Comment by Dokandres** [comment]
Resetting your graphics device will remove any leftover options or settings from previous plots. These might be causing undesired behavior or errors with your current plotting environment.

**Comment by liamxg** [comment]
@Dokandres thanks, I will try it.
